# Generated by Django 4.2.1 on 2023-06-30 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='Functionary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('cellphone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'person_type',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('id_functionary', models.ForeignKey(db_column='id_functionary', on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.functionary')),
                ('id_place', models.ForeignKey(db_column='id_place', on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.place')),
            ],
            options={
                'db_table': 'process',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('cellphone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('id_city_address', models.ForeignKey(db_column='id_city_address', on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.city')),
                ('id_depto_address', models.ForeignKey(db_column='id_depto_address', on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.department')),
                ('id_type_doc', models.ForeignKey(db_column='id_type_doc', on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.documenttype')),
                ('id_type_person', models.ForeignKey(db_column='id_type_person', on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.persontype')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.AddField(
            model_name='functionary',
            name='id_place',
            field=models.ForeignKey(db_column='id_place', on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.place'),
        ),
        migrations.AddField(
            model_name='functionary',
            name='id_type_doc',
            field=models.ForeignKey(db_column='id_type_doc', on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.documenttype'),
        ),
        migrations.AddField(
            model_name='city',
            name='id_department',
            field=models.ForeignKey(db_column='id_department', on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.department'),
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('id_person', models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.person')),
                ('id_process', models.ForeignKey(db_column='id_process', on_delete=django.db.models.deletion.DO_NOTHING, to='appointments.process')),
            ],
        ),
    ]
