# Generated by Django 4.2.1 on 2023-06-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_process_id_functionary_alter_process_id_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='id_functionary',
            field=models.ForeignKey(db_column='id_functionary', on_delete=django.db.models.deletion.CASCADE, to='appointments.functionary'),
        ),
        migrations.AlterField(
            model_name='process',
            name='id_place',
            field=models.ForeignKey(db_column='id_place', on_delete=django.db.models.deletion.CASCADE, to='appointments.place'),
        ),
    ]
