# Generated by Django 4.2.1 on 2023-07-06 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_process_id_functionary_alter_process_id_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='id_person',
            field=models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.PROTECT, to='appointments.person'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='id_process',
            field=models.ForeignKey(db_column='id_process', on_delete=django.db.models.deletion.PROTECT, to='appointments.process'),
        ),
        migrations.AlterField(
            model_name='city',
            name='id_department',
            field=models.ForeignKey(db_column='id_department', on_delete=django.db.models.deletion.PROTECT, to='appointments.department'),
        ),
        migrations.AlterField(
            model_name='functionary',
            name='id_place',
            field=models.ForeignKey(db_column='id_place', on_delete=django.db.models.deletion.PROTECT, to='appointments.place'),
        ),
        migrations.AlterField(
            model_name='functionary',
            name='id_type_doc',
            field=models.ForeignKey(db_column='id_type_doc', on_delete=django.db.models.deletion.PROTECT, to='appointments.documenttype'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_city_address',
            field=models.ForeignKey(db_column='id_city_address', on_delete=django.db.models.deletion.PROTECT, to='appointments.city'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_depto_address',
            field=models.ForeignKey(db_column='id_depto_address', on_delete=django.db.models.deletion.PROTECT, to='appointments.department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_type_doc',
            field=models.ForeignKey(db_column='id_type_doc', on_delete=django.db.models.deletion.PROTECT, to='appointments.documenttype'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_type_person',
            field=models.ForeignKey(db_column='id_type_person', on_delete=django.db.models.deletion.PROTECT, to='appointments.persontype'),
        ),
    ]
