# Generated by Django 4.2.1 on 2023-07-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_citation_id_person_alter_citation_id_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
