# Generated by Django 4.2.1 on 2023-07-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_citation_id_alter_state_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
