# Generated by Django 4.2.1 on 2023-07-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_process_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('time', models.IntegerField()),
                ('id_process', models.ForeignKey(db_column='id_process', on_delete=django.db.models.deletion.PROTECT, to='appointments.process')),
            ],
        ),
    ]
