# Generated by Django 4.2.1 on 2023-07-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='timetable',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
