# Generated by Django 4.2.1 on 2024-01-07 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_process_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='process',
            name='timetable',
            field=models.CharField(max_length=5000),
        ),
    ]
