# Generated by Django 4.2.1 on 2024-01-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_citation_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='status',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
